image: pulumi/pulumi-python:latest

stages:
  - build
  - deploy
variables:
  PULUMI_STACK_NAME: explorerstheatrecollective/cloudflare/prod
  PULUMI_WORKING_DIRECTORY: .

default:
  before_script:
    - |
      pushd ${PULUMI_WORKING_DIRECTORY}
      # Check if should use venv
      PULUMI_VENV=$(cat Pulumi.yaml | grep "virtualenv:" | cut -d':' -f2)
      if [ -z ${PULUMI_VENV} ]; then
          pip3 install -r requirements.txt
      else
          python3 -m venv ${PULUMI_VENV}
          ${PULUMI_VENV}/bin/python -m pip install --upgrade pip setuptools wheel
          ${PULUMI_VENV}/bin/python -m pip install -r requirements.txt
      fi
      popd

preview:
  stage: build
  script:
    - pulumi preview --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}
  only:
    - merge_requests

update:
  stage: deploy
  script:
    - pulumi up --yes --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}
  environment:
    name: cloudflare
    url: https://etcollective.org
  only:
    refs:
      - main
